### ISSUE TITLE
Add an Image Preview:

### ISSUE THREAD

**Issue by howdyGreens** [howdyGreens/plantIDer#3]
Si - add an image preview feature to the script.js file

similar example...where do you think it goes...

img id="imagePreview" src="" alt="Image Preview" style="display: none; max-width: 100%; margin-top: 20px; 

why did the skeleton not go to the dance...no <body> to go with... 👍

**Comment by w4ester** [comment]
Will reestablish LLM - kiddos are helping with this project...and also going to be able to use their modelFiles I set up for them (and see how they do regarding the parameters they agreed to regarding plant ID(er)...as A say's...lol!
