### ISSUE TITLE
Add this to script.js

### ISSUE THREAD

**Issue by howdyGreens** [howdyGreens/plantIDer#4]
const imageInput = document.getElementById('imageInput');
const imagePreview = document.getElementById('imagePreview');

imageInput.addEventListener('change', function() {
    const file = this.files[0];
    if (file) {
        const reader = new FileReader();
        reader.onload = function(e) {
            imagePreview.src = e.target.result;
            imagePreview.style.display = 'block';
        }
        reader.readAsDataURL(file);
    } else {
        imagePreview.style.display = 'none';
    }
});

**Comment by w4ester** [comment]
all set
